/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_davidguillen;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Canvas extends javax.swing.JFrame {

    /**
     * Creates new form Canvas
     */
    public Canvas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jP_Agregar4 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTF_Nombre = new javax.swing.JTextField();
        jTF_Edad = new javax.swing.JTextField();
        jTF_ID = new javax.swing.JTextField();
        jTF_IDB = new javax.swing.JTextField();
        jTF_Dinero = new javax.swing.JTextField();
        jCB_Departamento = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        jRB_Empleado = new javax.swing.JRadioButton();
        jRB_Estudiante = new javax.swing.JRadioButton();
        jRB_Politico = new javax.swing.JRadioButton();
        jB_Guardar = new javax.swing.JButton();
        jCB_Partidos = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jCB_Personas_Mod = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jP_Agregar5 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jTF_Nombre_Mod = new javax.swing.JTextField();
        jTF_Edad_Mod = new javax.swing.JTextField();
        jTF_ID_Mod = new javax.swing.JTextField();
        jTF_IDB_Mod = new javax.swing.JTextField();
        jTF_Dinero_Mod = new javax.swing.JTextField();
        jCB_Departamento_Mod = new javax.swing.JComboBox<>();
        jLabel42 = new javax.swing.JLabel();
        jRB_Empleado_Mod = new javax.swing.JRadioButton();
        jRB_Estudiante_Mod = new javax.swing.JRadioButton();
        jRB_Politico_Mod = new javax.swing.JRadioButton();
        jCB_Partidos_Mod = new javax.swing.JComboBox<>();
        jB_Guardar_Mod = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCB_Personas_Rep = new javax.swing.JComboBox<>();
        jB_Guardar_Eli = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jCB_Personas_Eli = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane2StateChanged(evt);
            }
        });

        jLabel29.setText("Nombre Completo");

        jLabel30.setText("Edad");

        jLabel31.setText("ID");

        jLabel32.setText("ID del Boleto");

        jLabel33.setText("Departamento");

        jLabel34.setText("Dinero en Bolsa");

        jTF_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_IDActionPerformed(evt);
            }
        });

        jCB_Departamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atlantida", "Colón", "Comayagua", "Copán", "Cortes", "Choluteca", "El Paraíso", "Francisco Morazán", "Gracias a Dios", "Intibucá", "Islas de la Bahía", "La Paz", "Lempira", "Ocotepeque", "Olancho", "Santa Bárbara", "Valle", "Yoro" }));

        jLabel35.setText("Estado ");

        buttonGroup1.add(jRB_Empleado);
        jRB_Empleado.setText("Empleado");
        jRB_Empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB_EmpleadoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRB_Estudiante);
        jRB_Estudiante.setText("Estudiante");

        buttonGroup1.add(jRB_Politico);
        jRB_Politico.setText("Politico");

        jB_Guardar.setText("Guardar");
        jB_Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_GuardarMouseClicked(evt);
            }
        });
        jB_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_GuardarActionPerformed(evt);
            }
        });

        jCB_Partidos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nacional", "Liberal", "PAC", "Pinu", "Libre" }));

        javax.swing.GroupLayout jP_Agregar4Layout = new javax.swing.GroupLayout(jP_Agregar4);
        jP_Agregar4.setLayout(jP_Agregar4Layout);
        jP_Agregar4Layout.setHorizontalGroup(
            jP_Agregar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_Agregar4Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jP_Agregar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_Guardar)
                    .addGroup(jP_Agregar4Layout.createSequentialGroup()
                        .addGroup(jP_Agregar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP_Agregar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTF_Nombre)
                            .addComponent(jTF_Edad)
                            .addComponent(jTF_ID)
                            .addComponent(jTF_IDB)
                            .addComponent(jCB_Departamento, 0, 138, Short.MAX_VALUE)
                            .addComponent(jTF_Dinero)))
                    .addGroup(jP_Agregar4Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB_Empleado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB_Estudiante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB_Politico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCB_Partidos, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(298, Short.MAX_VALUE))
        );
        jP_Agregar4Layout.setVerticalGroup(
            jP_Agregar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_Agregar4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jP_Agregar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jTF_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP_Agregar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jTF_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP_Agregar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jTF_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP_Agregar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jTF_IDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP_Agregar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jCB_Departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP_Agregar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jTF_Dinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP_Agregar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jRB_Empleado)
                    .addComponent(jRB_Estudiante)
                    .addComponent(jRB_Politico)
                    .addComponent(jCB_Partidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jB_Guardar)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 845, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jP_Agregar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jP_Agregar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Agregar", jPanel4);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Persona a Modificar");

        jLabel36.setText("Nombre Completo");

        jLabel37.setText("Edad");

        jLabel38.setText("ID");

        jLabel39.setText("ID del Boleto");

        jLabel40.setText("Departamento");

        jLabel41.setText("Dinero en Bolsa");

        jTF_ID_Mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_ID_ModActionPerformed(evt);
            }
        });

        jCB_Departamento_Mod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atlantida", "Colón", "Comayagua", "Copán", "Cortes", "Choluteca", "El Paraíso", "Francisco Morazán", "Gracias a Dios", "Intibucá", "Islas de la Bahía", "La Paz", "Lempira", "Ocotepeque", "Olancho", "Santa Bárbara", "Valle", "Yoro" }));

        jLabel42.setText("Estado ");

        buttonGroup1.add(jRB_Empleado_Mod);
        jRB_Empleado_Mod.setSelected(true);
        jRB_Empleado_Mod.setText("Empleado");
        jRB_Empleado_Mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB_Empleado_ModActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRB_Estudiante_Mod);
        jRB_Estudiante_Mod.setText("Estudiante");

        buttonGroup1.add(jRB_Politico_Mod);
        jRB_Politico_Mod.setText("Politico");

        jCB_Partidos_Mod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nacional", "Liberal", "PAC", "Pinu", "Libre" }));

        jB_Guardar_Mod.setText("Guardar");
        jB_Guardar_Mod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_Guardar_ModMouseClicked(evt);
            }
        });
        jB_Guardar_Mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Guardar_ModActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_Agregar5Layout = new javax.swing.GroupLayout(jP_Agregar5);
        jP_Agregar5.setLayout(jP_Agregar5Layout);
        jP_Agregar5Layout.setHorizontalGroup(
            jP_Agregar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_Agregar5Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jP_Agregar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_Guardar_Mod)
                    .addGroup(jP_Agregar5Layout.createSequentialGroup()
                        .addGroup(jP_Agregar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37)
                            .addComponent(jLabel38)
                            .addComponent(jLabel39)
                            .addComponent(jLabel40)
                            .addComponent(jLabel41))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP_Agregar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTF_Nombre_Mod)
                            .addComponent(jTF_Edad_Mod)
                            .addComponent(jTF_ID_Mod)
                            .addComponent(jTF_IDB_Mod)
                            .addComponent(jCB_Departamento_Mod, 0, 138, Short.MAX_VALUE)
                            .addComponent(jTF_Dinero_Mod)))
                    .addGroup(jP_Agregar5Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB_Empleado_Mod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB_Estudiante_Mod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB_Politico_Mod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCB_Partidos_Mod, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_Agregar5Layout.setVerticalGroup(
            jP_Agregar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_Agregar5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jP_Agregar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jTF_Nombre_Mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP_Agregar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jTF_Edad_Mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP_Agregar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jTF_ID_Mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP_Agregar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(jTF_IDB_Mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP_Agregar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jCB_Departamento_Mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP_Agregar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(jTF_Dinero_Mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP_Agregar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(jRB_Empleado_Mod)
                    .addComponent(jRB_Estudiante_Mod)
                    .addComponent(jRB_Politico_Mod)
                    .addComponent(jCB_Partidos_Mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jB_Guardar_Mod)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jCB_Personas_Mod, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jP_Agregar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCB_Personas_Mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jP_Agregar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Modificar", jPanel5);

        jLabel2.setText("Persona ");

        jB_Guardar_Eli.setText("Guardar");
        jB_Guardar_Eli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_Guardar_EliMouseClicked(evt);
            }
        });
        jB_Guardar_Eli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Guardar_EliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_Guardar_Eli)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCB_Personas_Rep, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCB_Personas_Rep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addComponent(jB_Guardar_Eli)
                .addContainerGap(288, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Eliminar", jPanel7);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Persona");

        jCB_Personas_Eli.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCB_Personas_EliItemStateChanged(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Nombre", "Edad", "ID ", "ID Boletos", "Departamento", "Dinero"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCB_Personas_Eli, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel3))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCB_Personas_Eli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Reportes", jPanel6);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 472, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Administrativa", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 874, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 874, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTF_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_IDActionPerformed

    private void jRB_EmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB_EmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRB_EmpleadoActionPerformed

    private void jB_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_GuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_GuardarActionPerformed

    private void jB_GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_GuardarMouseClicked
        String nombre,id,id_boletos, departamento, partido;
        int edad, dinero;
        String empleo = "";
        String carrera = "";
        try {
            if (jRB_Empleado.isSelected()) {
                nombre = jTF_Nombre.getText();
                edad = Integer.parseInt(jTF_Edad.getText());
                id = jTF_ID.getText();
                id_boletos = jTF_IDB.getText();
                departamento = jCB_Departamento.getSelectedItem().toString();
                dinero = Integer.parseInt(jTF_Dinero.getText());
                JOptionPane.showInputDialog("Ingrese Empleo:", empleo);
                lista.add(new Empleado(empleo, nombre, edad, id, id_boletos, departamento, dinero));
                JOptionPane.showMessageDialog(this, "Se ha agregado el contacto exitosamente");
                jTF_Nombre.setText("");
                jTF_Edad.setText("");
                jTF_ID.setText("");
                jTF_IDB.setText("");
                jCB_Departamento.setSelectedIndex(0);
                jTF_Dinero.setText("");
                empleo = "";
                carrera = "";
                jCB_Partidos.setSelectedIndex(0);
            } else if (jRB_Estudiante.isSelected()) {
                nombre = jTF_Nombre.getText();
                edad = Integer.parseInt(jTF_Edad.getText());
                id = jTF_ID.getText();
                id_boletos = jTF_IDB.getText();
                departamento = jCB_Departamento.getSelectedItem().toString();
                dinero = Integer.parseInt(jTF_Dinero.getText());
                JOptionPane.showInputDialog("Ingrese Carrera:", carrera);
                lista.add(new Estudiante(carrera, nombre, edad, id, id_boletos, departamento, dinero));
                JOptionPane.showMessageDialog(this, "Se ha agregado el contacto exitosamente");
                jTF_Nombre.setText("");
                jTF_Edad.setText("");
                jTF_ID.setText("");
                jTF_IDB.setText("");
                jCB_Departamento.setSelectedIndex(0);
                jTF_Dinero.setText("");
                empleo = "";
                carrera = "";
                jCB_Partidos.setSelectedIndex(0);
            } else if (jRB_Politico.isSelected()) {
                partido = jCB_Partidos.getSelectedItem().toString();
                nombre = jTF_Nombre.getText();
                edad = Integer.parseInt(jTF_Edad.getText());
                id = jTF_ID.getText();
                id_boletos = jTF_IDB.getText();
                departamento = jCB_Departamento.getSelectedItem().toString();
                dinero = Integer.parseInt(jTF_Dinero.getText());
                lista.add(new Politico(partido, nombre, edad, id, id_boletos, departamento, dinero));
                JOptionPane.showMessageDialog(this, "Se ha agregado el contacto exitosamente");
                jTF_Nombre.setText("");
                jTF_Edad.setText("");
                jTF_ID.setText("");
                jTF_IDB.setText("");
                jCB_Departamento.setSelectedIndex(0);
                jTF_Dinero.setText("");
                empleo = "";
                carrera = "";
                jCB_Partidos.setSelectedIndex(0);
            }
            
            
        } catch (Exception e) {
             e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        }
        
    }//GEN-LAST:event_jB_GuardarMouseClicked

    private void jTabbedPane2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane2StateChanged
        if (jTabbedPane2.getSelectedIndex() == 1 || jTabbedPane2.getSelectedIndex() == 2 || jTabbedPane2.getSelectedIndex() == 3) {
            DefaultComboBoxModel modelo
                    = new DefaultComboBoxModel();
            for (Persona t : lista) {
                modelo.addElement(t);
            }
            jCB_Personas_Mod.setModel(modelo);
            jCB_Personas_Eli.setModel(modelo);
            jCB_Personas_Rep.setModel(modelo);
        }
    }//GEN-LAST:event_jTabbedPane2StateChanged

    private void jTF_ID_ModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_ID_ModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_ID_ModActionPerformed

    private void jRB_Empleado_ModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB_Empleado_ModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRB_Empleado_ModActionPerformed

    private void jB_Guardar_ModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Guardar_ModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_Guardar_ModActionPerformed

    private void jB_Guardar_ModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_Guardar_ModMouseClicked
        String nombre,id,id_boletos, departamento, partido;
        int edad, dinero;
        String empleo = "";
        String carrera = "";
        try {
            if (jRB_Empleado_Mod.isSelected()) {
                int clik = jCB_Personas_Mod.getSelectedIndex();
                nombre = jTF_Nombre_Mod.getText();
                edad = Integer.parseInt(jTF_Edad_Mod.getText());
                id = jTF_ID_Mod.getText();
                id_boletos = jTF_IDB_Mod.getText();
                departamento = jCB_Departamento_Mod.getSelectedItem().toString();
                dinero = Integer.parseInt(jTF_Dinero_Mod.getText());
                JOptionPane.showInputDialog("Ingrese Empleo:", empleo);
                lista.set(clik, new Empleado(empleo, nombre, edad, id, id_boletos, departamento, dinero));
                JOptionPane.showMessageDialog(this, "Se ha modificado el contacto exitosamente");
                jTF_Nombre_Mod.setText("");
                jTF_Edad_Mod.setText("");
                jTF_ID_Mod.setText("");
                jTF_IDB_Mod.setText("");
                jCB_Departamento_Mod.setSelectedIndex(0);
                jTF_Dinero_Mod.setText("");
                empleo = "";
                carrera = "";
                jCB_Partidos.setSelectedIndex(0);
            } else if (jRB_Estudiante_Mod.isSelected()) {
                int clik = jCB_Personas_Mod.getSelectedIndex();
                nombre = jTF_Nombre_Mod.getText();
                edad = Integer.parseInt(jTF_Edad_Mod.getText());
                id = jTF_ID_Mod.getText();
                id_boletos = jTF_IDB_Mod.getText();
                departamento = jCB_Departamento_Mod.getSelectedItem().toString();
                dinero = Integer.parseInt(jTF_Dinero_Mod.getText());
                JOptionPane.showInputDialog("Ingrese Carrera:", carrera);
                lista.set(clik, new Estudiante(carrera, nombre, edad, id, id_boletos, departamento, dinero));
                JOptionPane.showMessageDialog(this, "Se ha modificado el contacto exitosamente");
                jTF_Nombre_Mod.setText("");
                jTF_Edad_Mod.setText("");
                jTF_ID_Mod.setText("");
                jTF_IDB_Mod.setText("");
                jCB_Departamento_Mod.setSelectedIndex(0);
                jTF_Dinero_Mod.setText("");
                empleo = "";
                carrera = "";
                jCB_Partidos.setSelectedIndex(0);
            } else if (jRB_Politico_Mod.isSelected()) {
                int clik = jCB_Personas_Mod.getSelectedIndex();
                partido = jCB_Partidos_Mod.getSelectedItem().toString();
                nombre = jTF_Nombre_Mod.getText();
                edad = Integer.parseInt(jTF_Edad_Mod.getText());
                id = jTF_ID_Mod.getText();
                id_boletos = jTF_IDB_Mod.getText();
                departamento = jCB_Departamento_Mod.getSelectedItem().toString();
                dinero = Integer.parseInt(jTF_Dinero_Mod.getText());
                lista.set(clik, new Politico(partido, nombre, edad, id, id_boletos, departamento, dinero));
                JOptionPane.showMessageDialog(this, "Se ha modificado el contacto exitosamente");
                jTF_Nombre_Mod.setText("");
                jTF_Edad_Mod.setText("");
                jTF_ID_Mod.setText("");
                jTF_IDB_Mod.setText("");
                jCB_Departamento_Mod.setSelectedIndex(0);
                jTF_Dinero_Mod.setText("");
                empleo = "";
                carrera = "";
                jCB_Partidos.setSelectedIndex(0);
            }
        } catch (Exception e) {
             e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        }
    }//GEN-LAST:event_jB_Guardar_ModMouseClicked

    private void jCB_Personas_EliItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCB_Personas_EliItemStateChanged
        if (evt.getStateChange() == 2) {
            int num=0;
            Persona s = (Persona) jCB_Personas_Eli.getSelectedItem();
            Object[] newrow = {
                num,
                s.getNombre(),
                s.getEdad(),
                s.getId(),
                s.getId_boletos(),
                s.getDepartamento(),
                s.getDinero(),
            };
            num++;
            DefaultTableModel modelo
                    = (DefaultTableModel) jTable1.getModel();
            modelo.addRow(newrow);
            jTable1.setModel(modelo);
        }
    }//GEN-LAST:event_jCB_Personas_EliItemStateChanged

    private void jB_Guardar_EliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Guardar_EliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_Guardar_EliActionPerformed

    private void jB_Guardar_EliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_Guardar_EliMouseClicked
        int rec = jCB_Personas_Rep.getSelectedIndex();
        lista.remove(rec);
    }//GEN-LAST:event_jB_Guardar_EliMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Canvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Canvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Canvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Canvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Canvas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jB_Guardar;
    private javax.swing.JButton jB_Guardar_Eli;
    private javax.swing.JButton jB_Guardar_Mod;
    private javax.swing.JComboBox<String> jCB_Departamento;
    private javax.swing.JComboBox<String> jCB_Departamento2;
    private javax.swing.JComboBox<String> jCB_Departamento_Mod;
    private javax.swing.JComboBox<String> jCB_Partidos;
    private javax.swing.JComboBox<String> jCB_Partidos_Mod;
    private javax.swing.JComboBox<String> jCB_Personas_Eli;
    private javax.swing.JComboBox<String> jCB_Personas_Mod;
    private javax.swing.JComboBox<String> jCB_Personas_Rep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JPanel jP_Agregar2;
    private javax.swing.JPanel jP_Agregar4;
    private javax.swing.JPanel jP_Agregar5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRB_Empleado;
    private javax.swing.JRadioButton jRB_Empleado_Mod;
    private javax.swing.JRadioButton jRB_Estudiante;
    private javax.swing.JRadioButton jRB_Estudiante_Mod;
    private javax.swing.JRadioButton jRB_Politico;
    private javax.swing.JRadioButton jRB_Politico_Mod;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF_Dinero;
    private javax.swing.JTextField jTF_Dinero2;
    private javax.swing.JTextField jTF_Dinero_Mod;
    private javax.swing.JTextField jTF_Edad;
    private javax.swing.JTextField jTF_Edad2;
    private javax.swing.JTextField jTF_Edad_Mod;
    private javax.swing.JTextField jTF_ID;
    private javax.swing.JTextField jTF_ID2;
    private javax.swing.JTextField jTF_IDB;
    private javax.swing.JTextField jTF_IDB2;
    private javax.swing.JTextField jTF_IDB_Mod;
    private javax.swing.JTextField jTF_ID_Mod;
    private javax.swing.JTextField jTF_Nombre;
    private javax.swing.JTextField jTF_Nombre2;
    private javax.swing.JTextField jTF_Nombre_Mod;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    ArrayList<Persona> lista = new ArrayList();
}
